linters:
  disable-all: true
  enable:
    # default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # extra useful linters
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - inamedparam
    - interfacebloat
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - usetesting
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    enable-all-rules: false
    rules:
      - name: exported
        disabled: false
      - name: blank-imports
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: context-keys-type
        disabled: false
      - name: dot-imports
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
      - name: if-return
        disabled: false
      - name: increment-decrement
        disabled: false
      - name: var-naming
        disabled: false
      - name: var-declaration
        disabled: false
      - name: package-comments
        disabled: false
      - name: range
        disabled: false
      - name: receiver-naming
        disabled: false
      - name: time-naming
        disabled: false
      - name: unexported-return
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: errorf
        disabled: false
      - name: empty-block
        disabled: false
      - name: superfluous-else
        disabled: false
      - name: confusing-naming
        disabled: false
      - name: get-return
        disabled: false
      - name: modifies-parameter
        disabled: false
      - name: confusing-results
        disabled: false
      - name: deep-exit
        disabled: false
      - name: unused-parameter
        disabled: false
      - name: unhandled-error
        disabled: false

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
